vich_uploader:
    db_driver: orm
    mappings:
        user_profile_picture:
            uri_prefix: /uploads/profile_pictures
            upload_destination: '%kernel.project_dir%/public/uploads/profile_pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
